<?php
namespace WRCInfrastructure\TemplateACFFields;

class TemplateACFFields
{
  public static function setupTemplateACFFields() {
    self::setupWRCHome();
    self::setup1stAutoHome();
    self::setupWRCAgencyHome();
    self::setupStatesServed();
    self::setupFindAnAgent();
    self::setupHelp();
    self::excludeFromLeftNav();
    self::fullwidthcontent();
  }
  private static function setupFindAnAgent()
  {
    if( function_exists('acf_add_local_field_group') ):

      acf_add_local_field_group(array (
        'key' => 'group_59d3d5475604b',
        'title' => 'Find an Agent',
        'fields' => array (
          array (
            'key' => 'field_59d3d55112a5b',
            'label' => 'Display Agents or Mutuals?',
            'name' => 'display_agents_or_mutuals',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array (
              'agent' => 'Agents',
              'mutual' => 'Mutuals',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'vertical',
            'return_format' => 'value',
          ),
          array (
            'key' => 'field_59d3d57212a5c',
            'label' => 'Background Hero Image',
            'name' => 'background_hero_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
          ),
          array (
            'key' => 'field_59d3d5a312a5d',
            'label' => 'Hero Content',
            'name' => 'hero_content',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'br',
          ),
        ),
        'location' => array (
          array (
            array (
              'param' => 'page_template',
              'operator' => '==',
              'value' => 'page-find-agent.php',
            ),
          ),
        ),
        'hide_on_screen' =>  array (
          0 => 'the_content',
          1 => 'excerpt',
          2 => 'custom_fields',
          3 => 'featured_image'
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'active' => 1,
        'description' => '',
      ));

      endif;
  }
  private static function setupWRCHome()
  {
    if( function_exists('acf_add_local_field_group') ){
      //Site Template
      acf_add_local_field_group(array(
        'key' => 'group_site_template',
        'title' => 'WRC Home Template',
        'fields' => array (
          array (
            'key' => 'field_wrc_home_template_site',
            'label' => 'Company Selection',
            'name' => 'site',
            'type' => 'post_object',
            'post_type' => 'site'
          ),
          array (
            'key' => 'field_wrc_home_hero_image',
            'label' => 'Hero Image',
            'name' => 'hero_image',
            'type' => 'image',
            'preview_size' => 'medium',
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'key' => 'field_wrc_home_hero_headline',
            'label' => 'Hero Headline',
            'name' => 'hero_headline',
            'type' => 'textarea',
            'new_lines' => 'br',
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'key' => 'field_wrc_home_hero_cta_link',
            'label' => 'Hero CTA Button Link',
            'name' => 'hero_cta_link',
            'type' => 'text',
            'instructions' => 'If linking to a section on this page, please add "#" before the section name. If linking off this page, please put in absolute link.',
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'key' => 'field_wrc_home_hero_cta_text',
            'label' => 'Hero CTA Button Text',
            'name' => 'hero_cta_text',
            'type' => 'text',
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array(
            'key' => 'field_wrc_home_subhead_section_id',
            'label' => 'Full Width Section ID',
            'name' => 'wrc_home_subhead_section_id',
            'type' => 'text',
            'instructions' => 'This text is used to link to this specific Full Width section. Add as lowercase text without spaces. Ex: section-insurance',
            'required' => 0,
          ),
          array (
            'key' => 'field_wrc_home_subhead',
            'label' => 'Full Width Headline',
            'name' => 'full_width_headline',
            'type' => 'text',
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'key' => 'field_wrc_home_subhead_content',
            'label' => 'Full Width Content',
            'name' => 'full_width_content',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
          ),
          array(
            'key' => 'field_bullet_section_id',
            'label' => 'Bullet Section ID',
            'name' => 'section_id',
            'type' => 'text',
            'instructions' => 'This text is used to link to this section from this page. Add as lowercase text without spaces. Ex: section-insurance',
            'required' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          //Customized Reinsurance Contracts section
          		array (
          			'key' => 'field_cr_background_image',
          			'label' => 'Background Image',
          			'name' => 'cr_background_image',
          			'type' => 'image',
                'return_format' => 'array',
          			'value' => NULL,
          			'instructions' => 'Optional Background Image',
          			'required' => 0,
          			'conditional_logic' => 0,
          			'wrapper' => array (
          				'width' => '',
          				'class' => '',
          				'id' => '',
          			),
          			'return_format' => 'array',
          			'preview_size' => 'thumbnail',
          			'library' => 'all',
          			'min_width' => '',
          			'min_height' => '',
          			'min_size' => '',
          			'max_width' => '',
          			'max_height' => '',
          			'max_size' => '',
          			'mime_types' => '',
          		),
          		array (
          			'key' => 'field_cr_headline',
          			'label' => 'Headline',
          			'name' => 'cr_headline',
          			'type' => 'text',
          			'value' => NULL,
          			'instructions' => '',
          			'required' => 0,
          			'conditional_logic' => 0,
          			'wrapper' => array (
          				'width' => '',
          				'class' => '',
          				'id' => '',
          			),
          			'default_value' => '',
          			'placeholder' => '',
          			'prepend' => '',
          			'append' => '',
          			'maxlength' => '',
          		),
          		array (
          			'key' => 'field_cr_content',
          			'label' => 'Content',
          			'name' => 'cr_content',
          			'type' => 'wysiwyg',
          			'value' => NULL,
          			'instructions' => '',
          			'required' => 0,
          			'conditional_logic' => 0,
          			'wrapper' => array (
          				'width' => '',
          				'class' => '',
          				'id' => '',
          			),
          			'default_value' => '',
          			'tabs' => 'all',
          			'toolbar' => 'full',
          			'media_upload' => 1,
          			'delay' => 0,
          		),
          		array (
          			'key' => 'field_cr_list_items',
          			'label' => 'List Items',
          			'name' => 'cr_list_items',
          			'type' => 'repeater',
          			'value' => NULL,
          			'instructions' => '',
          			'required' => 0,
          			'conditional_logic' => 0,
          			'wrapper' => array (
          				'width' => '',
          				'class' => '',
          				'id' => '',
          			),
          			'collapsed' => '',
          			'min' => 0,
          			'max' => 0,
          			'layout' => 'table',
          			'button_label' => '',
          			'sub_fields' => array (
          				array (
          					'key' => 'field_cr_item',
          					'label' => 'Item',
          					'name' => 'cr_item',
          					'type' => 'text',
          					'value' => NULL,
          					'instructions' => '',
          					'required' => 0,
          					'conditional_logic' => 0,
          					'wrapper' => array (
          						'width' => '',
          						'class' => '',
          						'id' => '',
          					),
          					'default_value' => '',
          					'placeholder' => '',
          					'prepend' => '',
          					'append' => '',
          					'maxlength' => '',
          				),
          			),
          		),
          //end Customized Reinsurance Contracts section
          array (
            'sub_fields' => array (
              array (
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'key' => 'field_598db96028274',
                'label' => 'Icon',
                'name' => 'icon',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '10',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_598db96b28275',
                'label' => 'Icon Text',
                'name' => 'icon_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
              //Start fields with conditional True/False field
              array (
          			'default_value' => 1,
          			'message' => '',
          			'ui' => 0,
          			'ui_on_text' => '',
          			'ui_off_text' => '',
          			'key' => 'field_59bbfca40167a',
          			'label' => 'Links to Content On Page',
          			'name' => 'icon_jump_link',
          			'type' => 'true_false',
          			'instructions' => '',
          			'required' => 0,
          			'conditional_logic' => 0,
          			'wrapper' => array (
          				'width' => '10',
          				'class' => '',
          				'id' => '',
          			),
          		),
          		array (
          			'default_value' => '',
          			'maxlength' => '',
          			'placeholder' => '',
          			'prepend' => '',
          			'append' => '',
          			'key' => 'field_59bbfc368a21b',
          			'label' => 'Link Target',
          			'name' => 'icon_link_target',
          			'type' => 'text',
          			'instructions' => 'Links to sections with matching ID from Fifty Fifty sections.',
          			'required' => 0,
          			'conditional_logic' => array (
          				array (
          					array (
          						'field' => 'field_59bbfca40167a',
          						'operator' => '==',
          						'value' => '1',
          					),
          				),
          			),
          		),
          		array (
          			'post_type' => array (
          			),
          			'taxonomy' => array (
          			),
          			'allow_null' => 0,
          			'multiple' => 0,
          			'allow_archives' => 1,
          			'key' => 'field_59bbfc4b8a21c',
          			'label' => 'Page Link',
          			'name' => 'icon_page_link',
          			'type' => 'page_link',
          			'instructions' => '',
          			'required' => 0,
          			'conditional_logic' => array (
          				array (
          					array (
          						'field' => 'field_59bbfca40167a',
          						'operator' => '!=',
          						'value' => '1',
          					),
          				),
          			),
          		),
              //end conditional fields
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'collapsed' => '',
            'key' => 'field_598db95028273',
            'label' => 'Assistance Icons',
            'name' => 'assistance_icons',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'sub_fields' => array (
              array(
                'key' => 'field_fiftyfifty_section_id',
                'label' => 'Section ID',
                'name' => 'section_id',
                'type' => 'text',
                'instructions' => 'This text is used to link to this section from the Assistance Icon links. Add as lowercase text without spaces. Ex: section-insurance',
                'required' => 0,
                'wrapper' => array (
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'key' => 'field_598dc43653901',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '15',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'default_value' => '',
                'delay' => 0,
                'key' => 'field_598dc43e53902',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => 'Add Section',
            'collapsed' => '',
            'key' => 'field_598dc3a753900',
            'label' => 'Fifty Fifty Sections',
            'name' => 'fifty_fifty_sections',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'sub_fields' => array (
              array (
                'key' => 'field_wrc_home_full_width_background_image_list',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'instructions' => 'Optional Background Image',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '10',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_598dd52bd9177',
                'label' => 'Headline',
                'name' => 'headline',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_content_order',
                'label' => 'Content Order',
                'name' => 'content_order',
                'type' => 'checkbox',
                'choices' => array(
                  'swap' => 'Swap order of Content and List Items'
                ),
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'key' => 'field_598dd530d9178',
                'label' => 'Content',
                'name' => 'subhead',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
              ),
              array (
                'sub_fields' => array (
                  array (
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'key' => 'field_598dd54cd917a',
                    'label' => 'Item',
                    'name' => 'item',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                  ),
                ),
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'collapsed' => '',
                'key' => 'field_598dd53ed9179',
                'label' => 'List Items',
                'name' => 'list_items',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => 'Add Bullet Section',
            'collapsed' => '',
            'key' => 'field_598dd51fd9176',
            'label' => 'Full Width Bullet Sections',
            'name' => 'full_width_bullet_sections',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
              'key' => 'field_1stauto_agent_search_image',
              'label' => 'Agent Search Image',
              'name' => 'agent_search_image',
              'type' => 'image'
            ),
           array (
              'key' => 'field_1stauto_agent_search_headline',
              'label' => 'Agent Search Headline',
              'name' => 'agent_search_headline',
              'type' => 'text'
            ),
            array (
              'key' => 'field_1stauto_agent_search_content',
              'label' => 'Agent Search Content',
              'name' => 'agent_search_content',
              'type' => 'textarea',
              'newline' => 'br'
            ),
            array (
              'key' => 'field_1stauto_agent_search_target',
              'label' => 'Agent Search Target Page',
              'name' => 'agent_search_target_page',
              'type' => 'page_link',
            ),
            array (
              'key' => 'field_1stauto_agent_search_linktext',
              'label' => 'Agent Search Link Text',
              'name' => 'agent_search_link_text',
              'type' => 'text',
            ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'page_template',
              'operator' => '==',
              'value' => 'page-wrc-home.php'
            )
          )
        ),
        'hide_on_screen' =>  array (
          0 => 'the_content',
          1 => 'excerpt',
          2 => 'custom_fields',
          3 => 'featured_image'
        )
      ));
    }
  }

  private static function setup1stAutoHome(){
    if( function_exists('acf_add_local_field_group') ){
      //Site Template
      acf_add_local_field_group(array(
        'key' => 'group_site_template_1stauto',
        'title' => '1st Auto Home Template',
        'fields' => array (
          array (
            'key' => 'field_1stauto_home_template_site',
            'label' => 'Company Selection',
            'name' => 'site',
            'type' => 'post_object',
            'post_type' => 'site'
          ),
          array (
            'key' => 'field_1stauto_home_hero_image',
            'label' => 'Hero Image',
            'name' => 'hero_image',
            'type' => 'image',
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'key' => 'field_1stauto_home_hero_headline',
            'label' => 'Hero Headline',
            'name' => 'hero_headline',
            'type' => 'textarea',
            'new_lines' => 'br',
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'sub_fields' => array (
              array (
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'key' => 'field_1stauto_home_card_icon',
                'label' => 'Icon',
                'name' => 'icon',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '5',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_1stauto_home_card_text',
                'label' => 'Icon Text',
                'name' => 'icon_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_1stauto_home_card_subtext',
                'label' => 'Icon Sub Text',
                'name' => 'icon_sub_text',
                'type' => 'text',
                'instructions' => 'Used if link is external or a modal.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '20',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array(
                'key' => 'field_1stauto_home_card_modal',
                'label' => 'Opens a Modal',
                'name' => 'icon_modal',
                'type' => 'select',
                'value' => NULL,
                'allow_null' => 1,
                'ui' => 1,
                'return_format' => 'value',
                //The choice values are the CSS classes used to open the modal
                'choices' => array(
                  'policy__modal-trigger'	=> 'My Policy Modal',
                  'bill__modal-trigger'	=> 'Bill Pay Modal',
                  'first-otto-link'	=> '1st Otto-mation Modal',
                ),
                  'wrapper' => array (
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                  ),
              ),
              // array (
              //   'default_value' => 0,
              //   'message' => 'Opens Bill Pay modal.',
              //   'ui' => 0,
              //   'ui_on_text' => '',
              //   'ui_off_text' => '',
              //   'key' => 'field_1stauto_home_card_modal',
              //   'label' => 'Opens Bill Pay modal?',
              //   'name' => 'icon_modal',
              //   'type' => 'true_false',
              //   'instructions' => 'Check this box if this icon opens the Bill Pay modal instead of linking to a page.',
              //   'required' => 0,
              //   'conditional_logic' => 0,
              //   'wrapper' => array (
              //     'width' => '15',
              //     'class' => '',
              //     'id' => '',
              //   ),
              // ),
              // array (
              //   'default_value' => 0,
              //   'message' => 'Opens 1st Otto-mation modal.',
              //   'ui' => 0,
              //   'ui_on_text' => '',
              //   'ui_off_text' => '',
              //   'key' => 'field_1stauto_home_card_otto_modal',
              //   'label' => 'Opens 1st Otto-mation modal?',
              //   'name' => 'icon_modal_otto',
              //   'type' => 'true_false',
              //   'instructions' => 'Check this box if this icon opens the 1st Otto-mation modal instead of linking to a page.',
              //   'required' => 0,
              //   'conditional_logic' => 0,
              //   'wrapper' => array (
              //     'width' => '15',
              //     'class' => '',
              //     'id' => '',
              //   ),
              // ),
              array (
                'post_type' => array (
                ),
                'taxonomy' => array (
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'allow_archives' => 1,
                'key' => 'field_1stauto_home_card_link',
                'label' => 'Icon Link',
                'name' => 'icon_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'collapsed' => '',
            'key' => 'field_1stauto_home_nav_cards',
            'label' => 'Navigation Icons',
            'name' => 'navigation_icons',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
          ),
          array(
            'key' => 'field_1stauto_home_section_id',
            'label' => 'Section ID',
            'name' => '1stauto_home_section_id',
            'type' => 'text',
            'instructions' => 'This text is used to link to this specific section. Add as lowercase text without spaces. Ex: section-insurance',
            'required' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'key' => 'field_1stauto_home_subhead',
            'label' => 'Subheader',
            'name' => 'subheader',
            'type' => 'text',
            'new_lines' => 'br',
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'sub_fields' => array (
              array (
                'key' => 'field_1stAuto_home_full_width_background_image_list',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'instructions' => 'Optional Background Image',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '10',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_1stauto_full_width_image_callout_headline',
                'label' => 'Headline',
                'name' => 'headline',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'default_value' => '',
                'new_lines' => 'br',
                'maxlength' => '',
                'placeholder' => '',
                'rows' => '',
                'key' => 'field_1stauto_full_width_callout_info',
                'label' => 'Info',
                'name' => 'info',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'key' => 'field_1stauto_full_width_callout_button_text',
                'label' => 'Button Text',
                'name' => 'button_text',
                'type' => 'text',
                'new_lines' => 'br'
              ),
              array (
                'key' => 'field_1stauto_full_width_callout_button_link',
                'label' => 'Button Link',
                'name' => 'button_link',
                'type' => 'url',
              ),
              array (
                'default_value' => 0,
                'message' => 'External Link',
                'key' => 'field_1stauto_full_width_callout_button_link_ext',
                'label' => 'External Link',
                'name' => 'button_link_ext',
                'type' => 'true_false',
                'instructions' => 'Check this box if this link is external.',
                'wrapper' => array (
                  'width' => '10',
                  'class' => '',
                  'id' => '',
                ),
              ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'collapsed' => '',
            'key' => 'field_1stauto_full_width_callout_sections',
            'label' => 'Full Width Callout Sections',
            'name' => 'full_width_callout_sections',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'key' => 'field_1stauto_home_protection_header',
            'label' => 'Protection Headline',
            'name' => 'protection_headline',
            'type' => 'text',
            'new_lines' => 'br'
          ),
          array (
            'key' => 'field_1stauto_home_protection_text',
            'label' => 'Protection Text',
            'name' => 'protection_text',
            'type' => 'textarea',
            'new_lines' => 'br'
          ),
          array (
            'sub_fields' => array (
              array (
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'key' => 'field_1stauto_home_protection_icon',
                'label' => 'Icon',
                'name' => 'icon',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'key' => 'field_1stauto_home_protection_icon_text',
                'label' => 'Icon Text',
                'name' => 'icon_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
              array (
                'post_type' => array (
                ),
                'taxonomy' => array (
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'allow_archives' => 1,
                'key' => 'field_1stauto_home_protection_icon_link',
                'label' => 'Icon Link',
                'name' => 'icon_link',
                'type' => 'page_link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'collapsed' => '',
            'key' => 'field_1stauto_home_protection_icons',
            'label' => 'Protection Icons',
            'name' => 'protection_icons',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'key' => 'field_1stauto_home_protection_button_text',
            'label' => 'Protection Button Text',
            'name' => 'protection_button_text',
            'type' => 'text',
            'new_lines' => 'br'
          ),
          array (
            'key' => 'field_1stauto_home_protection_button_link',
            'label' => 'Protection Button Link',
            'name' => 'protection_button_link',
            'type' => 'url',
          ),
          array (
            'key' => 'field_1stauto_home_mutuals_callout_headline',
            'label' => 'Mutuals Callout Headline',
            'name' => 'mutuals_callout_headline',
            'type' => 'text',
          ),
          array (
            'key' => 'field_1stauto_home_mutuals_callout_subhead',
            'label' => 'Mutuals Callout Subhead',
            'name' => 'mutuals_callout_subhead',
            'type' => 'textarea',
            'new_lines' => 'br'
          ),
          array (
            'key' => 'field_1stauto_home_mutuals_callout_background_image',
            'label' => 'Mutuals Callout Background Image',
            'name' => 'mutuals_callout_background_image',
            'type' => 'image'
          ),
          array (
            'key' => 'field_1stauto_home_mutuals_callout_button_text',
            'label' => 'Mutuals Callout Button Text',
            'name' => 'mutuals_callout_button_text',
            'type' => 'text',
          ),
          array (
            'key' => 'field_1stauto_home_mutuals_callout_button_link',
            'label' => 'Mutuals Callout Button Link',
            'name' => 'mutuals_callout_button_link',
            'type' => 'url',
          ),
          array (
              'key' => 'field_1stauto_agent_search_image',
              'label' => 'Agent Search Image',
              'name' => 'agent_search_image',
              'type' => 'image'
            ),
           array (
              'key' => 'field_1stauto_agent_search_headline',
              'label' => 'Agent Search Headline',
              'name' => 'agent_search_headline',
              'type' => 'text'
            ),
            array (
              'key' => 'field_1stauto_agent_search_content',
              'label' => 'Agent Search Content',
              'name' => 'agent_search_content',
              'type' => 'textarea',
              'newline' => 'br'
            ),
            array (
              'key' => 'field_1stauto_agent_search_target',
              'label' => 'Agent Search Target Page',
              'name' => 'agent_search_target_page',
              'type' => 'page_link',
            ),
            array (
              'key' => 'field_1stauto_agent_search_linktext',
              'label' => 'Agent Search Link Text',
              'name' => 'agent_search_link_text',
              'type' => 'text',
            ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'page_template',
              'operator' => '==',
              'value' => 'page-1stauto-home.php'
            )
          )
        ),
        'hide_on_screen' =>  array (
          0 => 'the_content',
          1 => 'excerpt',
          2 => 'custom_fields',
          3 => 'featured_image'
        )
      ));
    }
  }

  private static function setupWRCAgencyHome() {
    if( function_exists('acf_add_local_field_group') ){
      //Site Template
      acf_add_local_field_group(array(
        'key' => 'group_site_template_WRCAgencyHome',
      	'title' => 'WRC Agency Home',
      	'fields' => array (
          array (
            'key' => 'field_wrcagency_home_template_site',
            'label' => 'Company Selection',
            'name' => 'site',
            'type' => 'post_object',
            'post_type' => 'site'
          ),
      		array (
      			'default_value' => '',
      			'maxlength' => '',
      			'placeholder' => '',
      			'prepend' => '',
      			'append' => '',
      			'key' => 'field_wrc_agency_home_hero_headline',
      			'label' => 'Hero Headline',
      			'name' => 'hero_headline',
      			'type' => 'textarea',
            'new_lines' => 'br',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array (
      				'width' => '50',
      				'class' => '',
      				'id' => '',
      			),
      		),
      		array (
      			'max_size' => '0.5',
      			'key' => 'field_wrc_agency_home_hero_image',
      			'label' => 'Hero Image',
      			'name' => 'hero_image',
      			'type' => 'image',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array (
      				'width' => '50',
      				'class' => '',
      				'id' => '',
      			),
      		),
      		array (
      			'sub_fields' => array (
      				array (
      					'return_format' => 'array',
      					'preview_size' => 'thumbnail',
      					'library' => 'all',
      					'min_width' => '',
      					'min_height' => '',
      					'min_size' => '',
      					'max_width' => '',
      					'max_height' => '',
      					'max_size' => '0.5',
      					'mime_types' => '',
      					'key' => 'field_5992ed495de14',
      					'label' => 'Icon',
      					'name' => 'icon',
      					'type' => 'image',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array (
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
      				),
      				array (
      					'default_value' => '',
      					'maxlength' => '',
      					'placeholder' => '',
      					'prepend' => '',
      					'append' => '',
      					'key' => 'field_5992edb35de15',
      					'label' => 'Icon Text',
      					'name' => 'icon_text',
      					'type' => 'text',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array (
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
      				),
      				array (
      					'post_type' => array (
      					),
      					'taxonomy' => array (
      					),
      					'allow_null' => 0,
      					'multiple' => 0,
      					'allow_archives' => 1,
      					'key' => 'field_5992edd95de16',
      					'label' => 'Icon Link',
      					'name' => 'icon_link',
      					'type' => 'page_link',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array (
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
      				),
              array (
                'default_value' => 0,
                'message' => 'This icon opens a modal.',
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'key' => 'field_5994493cb3104',
                'label' => 'Opens modal?',
                'name' => 'icon_modal',
                'type' => 'true_false',
                'instructions' => 'Check this box if this icon opens a modal instead of linking to a page.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
      			),
      			'min' => 0,
      			'max' => 0,
      			'layout' => 'table',
      			'button_label' => '',
      			'collapsed' => '',
      			'key' => 'field_5992ed2c5de13',
      			'label' => 'Icon Callouts',
      			'name' => 'icon_callouts',
      			'type' => 'repeater',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array (
      				'width' => '',
      				'class' => '',
      				'id' => '',
      			),
      		),
          array(
            'key' => 'field_wrc_agency_protection_section_id',
            'label' => 'Section ID',
            'name' => 'wrc_agency_protection_section_id',
            'type' => 'text',
            'instructions' => 'This text is used to link to this specific section. Add as lowercase text without spaces. Ex: section-insurance',
            'required' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array(
            'key' => 'field_wrc_agency_protection_headline',
            'label' => 'Protection Headline',
            'name' => 'protection_headline',
            'type' => 'text',
            'required' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array(
            'key' => 'field_wrc_agency_personal_headline',
            'label' => 'Personal Insurance Headline',
            'name' => 'personal_insurance_headline',
            'type' => 'text',
            'required' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'max_size' => '0.5',
            'key' => 'field_wrc_agency_personal_image',
            'label' => 'Personal Insurance Image',
            'name' => 'personal_insurance_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array(
            'key' => 'field_wrc_agency_personal_subhead',
            'label' => 'Personal Insurance Subhead',
            'name' => 'personal_insurance_subhead',
            'type' => 'textarea',
            'required' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
      			'sub_fields' => array (
      				array (
      					'key' => 'field_59946e1165242',
      					'label' => 'List item',
      					'name' => 'list_item',
      					'type' => 'text',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array (
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
      				),
      			),
      			'min' => 0,
      			'max' => 0,
      			'layout' => 'table',
      			'button_label' => 'Add List Item',
      			'key' => 'field_59946cd765241',
      			'label' => 'Personal Lines List Items',
      			'name' => 'personal_list_items',
      			'type' => 'repeater',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array (
      				'width' => '50',
      				'class' => '',
      				'id' => '',
      			),
      		),

          array(
            'key' => 'field_wrc_agency_commercial_headline',
            'label' => 'Commercial Insurance Headline',
            'name' => 'commercial_insurance_headline',
            'type' => 'text',
            'required' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'max_size' => '0.5',
            'key' => 'field_wrc_agency_commercial_image',
            'label' => 'Commercial Insurance Image',
            'name' => 'commercial_insurance_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array(
            'key' => 'field_wrc_agency_commercial_subhead',
            'label' => 'Commercial Insurance Subhead',
            'name' => 'commercial_insurance_subhead',
            'type' => 'textarea',
            'required' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array (
            'sub_fields' => array (
              array (
                'key' => 'field_wrc_agency_commercial_list_item',
                'label' => 'List item',
                'name' => 'list_item',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
              ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add List Item',
            'key' => 'field_wrc_agency_commercial_list',
            'label' => 'Commercial Lines List Items',
            'name' => 'commercial_list_items',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),

          array(
            'key' => 'field_wrc_agency_agent_headline',
            'label' => 'Agent Programs Headline',
            'name' => 'agent_programs_headline',
            'type' => 'text',
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array(
            'key' => 'field_wrc_agency_agent_subhead',
            'label' => 'Agent Programs Subhead',
            'name' => 'agent_programs_subhead',
            'type' => 'textarea',
            'new_lines' => 'br',
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array(
            'key' => 'field_wrc_agency_agent_1stauto',
            'label' => '1st Auto Agents Content',
            'name' => 'agent_programs_1stauto',
            'type' => 'wysiwyg',
            'media_upload' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),
          array(
            'key' => 'field_wrc_agency_agent_direct',
            'label' => 'Direct Contract Content',
            'name' => 'agent_programs_direct',
            'type' => 'wysiwyg',
            'media_upload' => 0,
            'wrapper' => array (
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
          ),

      		array (
      			'default_value' => '',
      			'maxlength' => '',
      			'placeholder' => '',
      			'prepend' => '',
      			'append' => '',
      			'key' => 'field_5992ef3f2a0af',
      			'label' => 'Partnerships Headline',
      			'name' => 'partnerships_headline',
      			'type' => 'text',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array (
      				'width' => '50',
      				'class' => '',
      				'id' => '',
      			),
      		),
      		array (
      			'default_value' => '',
      			'maxlength' => '',
      			'placeholder' => '',
      			'prepend' => '',
      			'append' => '',
      			'key' => 'field_5992ef982a0b0',
      			'label' => 'Partnerships Subhead',
      			'name' => 'partnerships_subhead',
      			'type' => 'textarea',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array (
      				'width' => '50',
      				'class' => '',
      				'id' => '',
      			),
      		),
      		array (
      			'sub_fields' => array (
      				array (
      					'return_format' => 'array',
      					'preview_size' => 'thumbnail',
      					'library' => 'all',
      					'min_width' => '',
      					'min_height' => '',
      					'min_size' => '',
      					'max_width' => '',
      					'max_height' => '',
      					'max_size' => '0.5',
      					'mime_types' => '',
      					'key' => 'field_5992efd02a0b2',
      					'label' => 'Partner Icon',
      					'name' => 'partners_icon_img',
      					'type' => 'image',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array (
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
      				),
      				array (
      					'default_value' => '',
      					'placeholder' => '',
      					'key' => 'field_5992f1aa680d0',
      					'label' => 'Partnership Link',
      					'name' => 'partners_link',
      					'type' => 'url',
      					'instructions' => '',
      					'required' => 0,
      					'conditional_logic' => 0,
      					'wrapper' => array (
      						'width' => '',
      						'class' => '',
      						'id' => '',
      					),
      				),
      			),
      			'min' => 0,
      			'max' => 0,
      			'layout' => 'table',
      			'button_label' => '',
      			'collapsed' => '',
      			'key' => 'field_5992efbd2a0b1',
      			'label' => 'Partnerships Icons',
      			'name' => 'partners_icons',
      			'type' => 'repeater',
      			'instructions' => '',
      			'required' => 0,
      			'conditional_logic' => 0,
      			'wrapper' => array (
      				'width' => '',
      				'class' => '',
      				'id' => '',
      			),
      		),
      	),
      	'location' => array (
      		array (
      			array (
      				'param' => 'page_template',
      				'operator' => '==',
      				'value' => 'page-wrc-agency-home.php',
      			),
      		),
      	),
      	'menu_order' => 0,
      	'position' => 'normal',
      	'style' => 'default',
      	'label_placement' => 'top',
      	'instruction_placement' => 'label',
      	'hide_on_screen' => array (
          0 => 'the_content',
          1 => 'excerpt',
          2 => 'custom_fields',
          3 => 'featured_image'
        ),
      	'active' => 1,
      	'description' => '',
      ));
    }
  }

  private static function setupStatesServed() {
    if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
    	'key' => 'group_states_served',
    	'title' => 'States Served Module',
    	'fields' => array (
        array (
          'max_size' => '0.5',
          'key' => 'field_state_served_image',
          'return_format' => 'array',
          'label' => 'Background Image',
          'name' => 'state_served_bg_image',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'wrapper' => array (
            'width' => '10',
            'class' => '',
            'id' => '',
          ),
        ),
    		array (
    			'key' => 'field_59a6fc058ebc3',
    			'label' => 'Header',
    			'name' => 'state_served_header',
    			'type' => 'text',
    			'instructions' => '',
    			'required' => 0,
    			'wrapper' => array (
    				'width' => '40',
    				'class' => '',
    				'id' => '',
    			),
    		),
    		array (
    			'new_lines' => 'wpautop',
    			'rows' => '',
    			'key' => 'field_59a6fc1a8ebc4',
    			'label' => 'Content',
    			'name' => 'state_served_content',
    			'type' => 'textarea',
    			'instructions' => '',
    			'required' => 0,
    			'wrapper' => array (
    				'width' => '50',
    				'class' => '',
    				'id' => '',
    			),
    		),
    	),
    	'location' => array (
    		array (
    			array (
    				'param' => 'page_template',
    				'operator' => '==',
    				'value' => 'page-wrc-agency-home.php',
    			),
    		),
    	),
    	'menu_order' => 0,
    	'position' => 'normal',
    	'style' => 'default',
    	'label_placement' => 'top',
    	'instruction_placement' => 'label',
    	'hide_on_screen' => '',
    	'active' => 1,
    	'description' => '',
    ));

    endif;
  }

  private static function setupHelp() {
    if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
      'key' => 'group_59d6585a31838',
      'title' => 'Help',
      'fields' => array (
        array (
          'key' => 'field_59d6585f8d532',
          'label' => 'Help Questions',
          'name' => 'help_questions',
          'type' => 'repeater',
          'instructions' => 'Select as many help questions as you\'d like to appear',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'collapsed' => '',
          'min' => 0,
          'max' => 0,
          'layout' => 'table',
          'button_label' => '',
          'sub_fields' => array (
            array (
              'key' => 'field_59d658768d533',
              'label' => 'Help',
              'name' => 'help',
              'type' => 'post_object',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
                0 => 'help',
              ),
              'taxonomy' => array (
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'return_format' => 'object',
              'ui' => 1,
            ),
          ),
        ),
      ),
      'location' => array (
        array (
          array (
            'param' => 'page_template',
            'operator' => '==',
            'value' => 'page-help.php',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    ));

    endif;
  }
  private static function excludeFromLeftNav() {
    if( function_exists('acf_add_local_field_group') ):
      acf_add_local_field_group(array (
          'key' => 'group_exclude_from_left_nav',
          'title' => 'Exclude From Left Navigation',
          'fields' => array (
            array(
              'key' => 'field_exclude_from_left_nav',
              'name' => 'exclude_from_left_nav',
              'type' => 'true_false',
              'default_value' => '0', //should be false (not excluded by default)
              'message' => 'Select if you want to exclude this Page from appearing in the Left Navigation menu.',
            ),
          ),
          'position' => 'side',
          'location' => array(
          		array(
          			array(
          				'param' => 'page_template',
          				'operator' => '==',
          				'value' => 'default',
          			),
          		),
              array(
                array(
                  'param' => 'page_template',
                  'operator' => '==',
                  'value' => 'page-news.php',
                ),
              ),
              array(
                array(
                  'param' => 'page_template',
                  'operator' => '==',
                  'value' => 'page-careers.php',
                ),
              ),
              array(
                array(
                  'param' => 'page_template',
                  'operator' => '==',
                  'value' => 'page-global.php',
                ),
              ),
              array(
                array(
                  'param' => 'page_template',
                  'operator' => '==',
                  'value' => 'page-1stauto-home.php',
                ),
              ),
              array(
                array(
                  'param' => 'page_template',
                  'operator' => '==',
                  'value' => 'page-wrc-agency-home.php',
                ),
              ),
              array(
                array(
                  'param' => 'page_template',
                  'operator' => '==',
                  'value' => 'page-wrc-home.php',
                ),
              ),
              array(
                array(
                  'param' => 'page_template',
                  'operator' => '==',
                  'value' => 'page-find-agent.php',
                ),
              ),
          		array(
          			array(
          				'param' => 'page_template',
          				'operator' => '==',
          				'value' => 'page-help.php',
          			),
          		),
          	),
        ));
    endif;
  }

  private static function fullwidthcontent() {
      if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array(
          'key' => 'group_5e90ccc68d15e',
          'title' => 'Full Width Page',
          'fields' => array(
            array(
              'key' => 'field_5e90cd46c3c7a',
              'label' => 'Columns',
              'name' => 'columns',
              'type' => 'radio',
              'instructions' => 'How many columns will this page need?',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                1 => '1',
                2 => '2',
              ),
              'allow_null' => 1,
              'other_choice' => 0,
              'default_value' => 1,
              'layout' => 'vertical',
              'return_format' => 'value',
              'save_other_choice' => 0,
            ),
            array(
              'key' => 'field_5e90cf5fc3c80',
              'label' => 'Full Width Content',
              'name' => 'full_width_content',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_5e90cd46c3c7a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array(
              'key' => 'field_5e90ce36c3c7b',
              'label' => 'Left Column',
              'name' => '',
              'type' => 'tab',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_5e90cd46c3c7a',
                    'operator' => '==',
                    'value' => '2',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'placement' => 'top',
              'endpoint' => 0,
            ),
            array(
              'key' => 'field_5e90ce4cc3c7c',
              'label' => 'left Content',
              'name' => 'left_content',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array(
              'key' => 'field_5e90cf0dc3c7e',
              'label' => 'Right Column',
              'name' => '',
              'type' => 'tab',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array(
                array(
                  array(
                    'field' => 'field_5e90cd46c3c7a',
                    'operator' => '==',
                    'value' => '2',
                  ),
                ),
              ),
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'placement' => 'top',
              'endpoint' => 0,
            ),
            array(
              'key' => 'field_5e90cf41c3c7f',
              'label' => 'Right Content',
              'name' => 'right_content',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array(
              'key' => 'field_5e90ce77c3c7d',
              'label' => 'Form Shortcode',
              'name' => 'form_shortcode',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
          ),
          'location' => array(
            array(
              array(
                'param' => 'post_template',
                'operator' => '==',
                'value' => 'full-width.php',
              ),
            ),
          ),
          'menu_order' => 0,
          'position' => 'acf_after_title',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => array(
            0 => 'the_content',
          ),
          'active' => true,
          'description' => '',
        ));

        endif;
        }

}
